Libraries=fixed_float ocpi axi sdp platform

SourceFiles= \
    zynq_ultra_zrf8_48dr_pkg.vhd \
    zynq_ultra_zrf8_48dr_ps.vhd \
    design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.dcp

OnlyTargets=zynq_ultra

include $(OCPI_CDK_DIR)/include/hdl/hdl-library.mk
